
# scans for new wifi networks and output sorted list of ESSIDs
alias wifiscan="sudo iwlist wlan0 scan | grep ESSID: | sed 's/.*ESSID:\"\(.*\)\"/  \1/' | sort"

# git
alias gits="git status"
alias gitl="git log --date-order --date=iso --graph --full-history --all --pretty=format:'%x08%x09%C(red)%h %C(cyan)%ad%x08%x08%x08%x08%x08%x08%x08%x08%x08 %C(bold blue)%aN%C(reset)%C(bold yellow)%d %C(reset)%s'"
